import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import helmet from 'helmet';
import compression from 'compression';
import rateLimit from 'express-rate-limit';
import cors from 'cors';
import mongoose from 'mongoose';

// --- Configuration ---
const PORT = process.env.PORT || 3000;
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/jayamurugan';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();

// --- Security Middleware ---
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: ["'self'", "'unsafe-inline'", "https://maps.googleapis.com"],
      styleSrc: ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
      fontSrc: ["'self'", "https://fonts.gstatic.com"],
      imgSrc: ["'self'", "data:", "https:", "blob:"],
      frameSrc: ["'self'", "https://www.google.com"], // For Maps
      connectSrc: ["'self'", "https://api.whatsapp.com"],
    },
  },
}));

// Rate Limiting (DDoS protection)
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100, // Limit each IP to 100 requests per windowMs
  standardHeaders: true,
  legacyHeaders: false,
});
app.use('/api', limiter);

app.use(compression()); // Compress responses
app.use(cors()); // Cross-Origin Resource Sharing
app.use(express.json()); // Parse JSON bodies

// --- Database Connection (Optional/MERN requirement) ---
// Note: Ensure MongoDB is running locally or provide a connection string
mongoose.connect(MONGODB_URI)
  .then(() => console.log('✅ Connected to MongoDB'))
  .catch(err => console.warn('⚠️ MongoDB connection warning (Running in static mode):', err.message));

// Schema Definition (Example)
const EnquirySchema = new mongoose.Schema({
  name: String,
  email: String,
  phone: String,
  message: String,
  date: { type: Date, default: Date.now }
});
const Enquiry = mongoose.model('Enquiry', EnquirySchema);

// --- API Routes ---
app.post('/api/contact', async (req, res) => {
  try {
    const { name, email, phone, message } = req.body;
    
    // Basic Server-side Validation
    if (!name || !email || !phone) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    // Save to DB (if connected)
    if (mongoose.connection.readyState === 1) {
      const newEnquiry = new Enquiry({ name, email, phone, message });
      await newEnquiry.save();
    }

    return res.status(200).json({ success: true, message: 'Enquiry received successfully' });
  } catch (error) {
    console.error('API Error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
});

// --- Serve Static Frontend ---
// Serves the 'dist' folder generated by 'npm run build'
app.use(express.static(path.join(__dirname, 'dist')));

// Handle React Routing (SPA fallback)
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

// --- Start Server ---
app.listen(PORT, () => {
  console.log(`🚀 Server running on http://localhost:${PORT}`);
  console.log(`🔒 Security headers enabled`);
});